import type { LayoutBundle } from "./types";

export const layouts: Record<string, LayoutBundle> = {
  thyroidectomy: {
    entities: [
      { id: "humanoid_body", type: "humanoid", x: 31, y: 44, width: 18, height: 28, label: "Humanoid Assistant" },
      { id: "surgeon_actor", type: "surgeon", x: 72, y: 36, width: 16, height: 24, label: "Surgeon" },
      { id: "thyroid_bed", type: "surgical_bed", x: 56, y: 50, width: 28, height: 20, label: "OR Bed" },
      { id: "instrument_rack", type: "instrument_rack", x: 12, y: 56, width: 20, height: 24, label: "Instrument Rack" },
      { id: "mayo_stand", type: "mayo_stand", x: 56, y: 64, width: 24, height: 8, label: "Mayo Stand" },
      { id: "cleaner_station", type: "cleaner_station", x: 21, y: 28, width: 12, height: 12, label: "Cleaner" },
      { id: "unknown_zone", type: "unknown_zone", x: 88, y: 62, width: 10, height: 8, label: "Unresolved" },
    ],
    anchors: [
      { id: "robot_right_hand", attached_to: "humanoid_body", x: 42, y: 41, label: "Right Hand" },
      { id: "robot_left_hand", attached_to: "humanoid_body", x: 28, y: 47, label: "Left Hand" },
      { id: "surgeon_receive_zone", attached_to: "surgeon_actor", x: 66, y: 43, label: "Receive Zone" },
      { id: "surgeon_return_zone", attached_to: "surgeon_actor", x: 66, y: 53, label: "Return Zone" },
      { id: "cleaner_slot", attached_to: "cleaner_station", x: 24, y: 31, label: "Cleaner Slot" },
      { id: "surgeon_hand", attached_to: "surgeon_actor", x: 69, y: 47, label: "Surgeon Hand" },
      { id: "field_region_thyroid", attached_to: "thyroid_bed", x: 57, y: 49, label: "Thyroid Field" },
      { id: "mayo_recovery_zone", attached_to: "mayo_stand", x: 50, y: 64, label: "Recovery Zone" },
      { id: "mayo_reuse_zone", attached_to: "mayo_stand", x: 62, y: 64, label: "Reuse Zone" },
      { id: "unknown_zone_anchor", attached_to: "unknown_zone", x: 93, y: 66, label: "Unresolved" },
      { id: "main_tray_slot_1", attached_to: "instrument_rack", x: 15, y: 61 },
      { id: "main_tray_slot_2", attached_to: "instrument_rack", x: 20, y: 61 },
      { id: "main_tray_slot_3", attached_to: "instrument_rack", x: 25, y: 61 },
      { id: "main_tray_slot_4", attached_to: "instrument_rack", x: 15, y: 68 },
      { id: "main_tray_slot_5", attached_to: "instrument_rack", x: 20, y: 68 },
      { id: "main_tray_slot_6", attached_to: "instrument_rack", x: 25, y: 68 },
    ],
  },
  nephrectomy: {
    entities: [
      { id: "humanoid_body", type: "humanoid", x: 30, y: 45, width: 18, height: 28, label: "Humanoid Assistant" },
      { id: "surgeon_actor", type: "surgeon", x: 73, y: 37, width: 16, height: 24, label: "Surgeon" },
      { id: "nephrectomy_bed", type: "surgical_bed", x: 57, y: 50, width: 30, height: 20, label: "OR Bed" },
      { id: "instrument_rack", type: "instrument_rack", x: 12, y: 55, width: 22, height: 26, label: "Instrument Rack" },
      { id: "mayo_stand", type: "mayo_stand", x: 57, y: 64, width: 24, height: 8, label: "Mayo Stand" },
      { id: "cleaner_station", type: "cleaner_station", x: 22, y: 27, width: 12, height: 12, label: "Cleaner" },
      { id: "unknown_zone", type: "unknown_zone", x: 88, y: 62, width: 10, height: 8, label: "Unresolved" },
    ],
    anchors: [
      { id: "robot_right_hand", attached_to: "humanoid_body", x: 41, y: 42, label: "Right Hand" },
      { id: "robot_left_hand", attached_to: "humanoid_body", x: 28, y: 48, label: "Left Hand" },
      { id: "surgeon_receive_zone", attached_to: "surgeon_actor", x: 67, y: 44, label: "Receive Zone" },
      { id: "surgeon_return_zone", attached_to: "surgeon_actor", x: 67, y: 54, label: "Return Zone" },
      { id: "cleaner_slot", attached_to: "cleaner_station", x: 25, y: 30, label: "Cleaner Slot" },
      { id: "surgeon_hand", attached_to: "surgeon_actor", x: 70, y: 47, label: "Surgeon Hand" },
      { id: "field_region_kidney_hilum", attached_to: "nephrectomy_bed", x: 58, y: 49, label: "Kidney Hilum" },
      { id: "mayo_recovery_zone", attached_to: "mayo_stand", x: 51, y: 64, label: "Recovery Zone" },
      { id: "mayo_reuse_zone", attached_to: "mayo_stand", x: 63, y: 64, label: "Reuse Zone" },
      { id: "unknown_zone_anchor", attached_to: "unknown_zone", x: 93, y: 66, label: "Unresolved" },
      { id: "main_tray_slot_1", attached_to: "instrument_rack", x: 15, y: 60 },
      { id: "main_tray_slot_2", attached_to: "instrument_rack", x: 20, y: 60 },
      { id: "main_tray_slot_3", attached_to: "instrument_rack", x: 25, y: 60 },
      { id: "main_tray_slot_4", attached_to: "instrument_rack", x: 30, y: 60 },
      { id: "main_tray_slot_5", attached_to: "instrument_rack", x: 15, y: 68 },
      { id: "main_tray_slot_6", attached_to: "instrument_rack", x: 20, y: 68 },
      { id: "main_tray_slot_7", attached_to: "instrument_rack", x: 25, y: 68 },
      { id: "main_tray_slot_8", attached_to: "instrument_rack", x: 30, y: 68 },
    ],
  },
};
