string command_id
string action
string instrument_id
string instrument_instance_id
string target_location_id
string target_location_type
string rationale
string arm
string source_location_id
string source_location_type
string target_owner
bool cleaning_required
string mode
---
bool success
string state
string message
surgical_msgs/TwinEvent resulting_event
---
string state
float32 progress
string message
