import type { Language } from "./display";

export function getUiCopy(language: Language) {
  return language === "ko"
    ? {
        appName: "수술실 디지털 트윈",
        eyebrow: "태스크플래너 v1",
        language: "언어",
        korean: "한국어",
        english: "English",
        rosOnline: "ROS 연결",
        rosConnecting: "ROS 연결 중",
        rosWaiting: "ROS 상태 대기",
        rosOffline: "ROS 끊김",
        procedure: "프로시저",
        currentState: "현재 상태",
        surgery: "수술",
        control: "제어",
        start: "수술 시작",
        pause: "일시정지",
        paused: "일시정지",
        resume: "재생",
        reset: "초기화",
        stop: "정지",
        preparing: "준비 중",
        starting: "시작 중",
        finishing: "정리 중",
        completed: "완료",
        using: "사용중",
        contaminated: "오염",
        requestedBadge: "요청",
        predictedBadge: "예측",
        waitingState: "대기",
        handoverState: "전달",
        recoveryState: "회수",
        cleaningState: "세척",
        returnedState: "대기",
        timelineLog: "이벤트 로그",
        phaseOverview: "수술 단계",
        interruptAlertTitle: "인터럽트 이벤트",
        applyBundle: "번들 적용",
        selectSurgery: "수술 선택",
        startPhase: "시작 단계",
        fromBeginning: "처음부터",
        bridgeUrl: "ROS 브리지",
        currentPhase: "현재 단계",
        robotTask: "로봇 작업",
        actionPanel: "행동",
        cleaner: "클리너",
        idle: "대기",
        running: "실행 중",
        halted: "정지",
        busy: "작동 중",
        none: "없음",
        surgeonIntent: "집도의 의도",
        requestedTool: "요청 도구",
        spoken: "발화",
        handover: "전달 준비",
        retrieval: "회수 준비",
        overrideTool: "오버라이드 도구",
        voiceText: "음성 텍스트",
        requestTool: "도구 요청",
        voiceOverride: "음성 오버라이드",
        returnTool: "도구 반환",
        stageTitle: "수술실 스테이지",
        stageHint: "도구 위치, 손 점유, 세척/회수 흐름",
        instrumentRack: "도구 랙",
        humanoid: "휴머노이드",
        surgeon: "집도의",
        surgicalBed: "수술베드",
        cleanerStation: "클리너",
        mayoStand: "메이요 스탠드",
        recovery: "회수",
        reuse: "재사용",
        timeline: "이벤트 타임라인",
        timelineFilter: "타임라인 필터",
        timelineAll: "전체",
        timelineNormal: "일반",
        timelineWarning: "경고",
        timelineError: "오류",
        observability: "판단 레이어",
        bt: "BT",
        vlm: "VLM",
        skill: "Skill",
        selectedTool: "선택 도구",
        lifecycle: "라이프사이클",
        nextTransition: "다음 전이",
        guard: "가드",
        rationale: "근거",
        progress: "진행률",
        connection: "연결",
        health: "상태",
        model: "모델",
        mode: "모드",
        source: "소스",
        imageSource: "이미지 소스",
        latency: "지연",
        gesture: "제스처",
        reducer: "리듀서",
        rawResult: "Raw VLM",
        yes: "예",
        no: "아니오",
      }
    : {
        appName: "OR Digital Twin",
        eyebrow: "TaskPlanner v1",
        language: "Language",
        korean: "한국어",
        english: "English",
        rosOnline: "ROS Online",
        rosConnecting: "ROS Connecting",
        rosWaiting: "ROS state pending",
        rosOffline: "ROS Offline",
        procedure: "Procedure",
        currentState: "Current State",
        surgery: "Surgery",
        control: "Control",
        start: "Start surgery",
        pause: "Pause",
        paused: "paused",
        resume: "Resume",
        reset: "Reset",
        stop: "Stop",
        preparing: "Preparing",
        starting: "starting",
        finishing: "finishing",
        completed: "completed",
        using: "Using",
        contaminated: "Contaminated",
        requestedBadge: "Requested",
        predictedBadge: "Predicted",
        waitingState: "Waiting",
        handoverState: "Handover",
        recoveryState: "Recovery",
        cleaningState: "Cleaning",
        returnedState: "Waiting",
        timelineLog: "Event Log",
        phaseOverview: "Procedure phases",
        interruptAlertTitle: "Interrupt Event",
        applyBundle: "Apply Bundle",
        selectSurgery: "Select Surgery",
        startPhase: "Start Phase",
        fromBeginning: "From beginning",
        bridgeUrl: "ROS Bridge",
        currentPhase: "Current Phase",
        robotTask: "Robot Task",
        actionPanel: "Action",
        cleaner: "Cleaner",
        idle: "idle",
        running: "running",
        halted: "halted",
        busy: "busy",
        none: "none",
        surgeonIntent: "Surgeon Intent",
        requestedTool: "Requested Tool",
        spoken: "Spoken",
        handover: "Handover Ready",
        retrieval: "Retrieval Ready",
        overrideTool: "Override Tool",
        voiceText: "Voice Text",
        requestTool: "Request Tool",
        voiceOverride: "Voice Override",
        returnTool: "Return Tool",
        stageTitle: "Operating Room Stage",
        stageHint: "Tool position, hand possession, cleaning and recovery flow",
        instrumentRack: "Instrument Rack",
        humanoid: "Humanoid",
        surgeon: "Lead Surgeon",
        surgicalBed: "Surgical Bed",
        cleanerStation: "Cleaner",
        mayoStand: "Mayo stand",
        recovery: "Recovery",
        reuse: "Reuse",
        timeline: "Event Timeline",
        timelineFilter: "Timeline filter",
        timelineAll: "All",
        timelineNormal: "General",
        timelineWarning: "Warning",
        timelineError: "Error",
        observability: "Explainability Layer",
        bt: "BT",
        vlm: "VLM",
        skill: "Skill",
        selectedTool: "Selected Tool",
        lifecycle: "Lifecycle",
        nextTransition: "Next Transition",
        guard: "Guard",
        rationale: "Rationale",
        progress: "Progress",
        connection: "Connection",
        health: "Health",
        model: "Model",
        mode: "Mode",
        source: "Source",
        imageSource: "Image Source",
        latency: "Latency",
        gesture: "Gesture",
        reducer: "Reducer",
        rawResult: "Raw VLM",
        yes: "yes",
        no: "no",
      };
}
